// One-off generator: embed art/coral-atlas-128.png as a base64 data URL in
// src/coralsAtlas.ts, and bake the sprite layout + tight bounding boxes from
// art/coral-atlas-128.json. Re-run if the source atlas or JSON changes.
import { readFileSync, writeFileSync } from "node:fs";
import { decodePng } from "./png";

const SRC_PNG  = "art/coral-atlas-128.png";
const SRC_JSON = "art/coral-atlas-128.json";
const OUT      = "src/coralsAtlas.ts";

const pngBuf = readFileSync(SRC_PNG);
const b64 = pngBuf.toString("base64");
const { rgba, w } = decodePng(pngBuf);
const json = JSON.parse(readFileSync(SRC_JSON, "utf8"));

const cell: number = json.tileSize;
const cols: number = json.columns;
const rows: number = json.rows;

// Compute the tight vertical extent (top/bottom opaque row) of each sprite's
// main body so coralBlits() can rest the coral's real base on the sand.
// Opaque rows are grouped into vertical bands separated by transparent gaps and
// the heaviest band wins, so stray pixels stranded against a cell edge (atlas
// bleed) can't inflate the box and float the coral off the sand.
const ALPHA_MIN = 4;
const GAP_BREAK = 8;
function contentRows(row: number, col: number): { top: number; bottom: number } {
  const x0 = col * cell;
  const y0 = row * cell;
  const count: number[] = [];
  for (let y = 0; y < cell; y++) {
    let c = 0;
    for (let x = 0; x < cell; x++) {
      if (rgba[((y0 + y) * w + (x0 + x)) * 4 + 3] > ALPHA_MIN) c++;
    }
    count.push(c);
  }
  type Band = { top: number; bottom: number; mass: number };
  const bands: Band[] = [];
  let last = -GAP_BREAK - 1;
  for (let y = 0; y < cell; y++) {
    if (count[y] === 0) continue;
    if (bands.length && y - last <= GAP_BREAK) {
      const b = bands[bands.length - 1];
      b.bottom = y;
      b.mass += count[y];
    } else {
      bands.push({ top: y, bottom: y, mass: count[y] });
    }
    last = y;
  }
  if (!bands.length) return { top: 0, bottom: cell - 1 };
  const best = bands.reduce((a, b) => (b.mass > a.mass ? b : a));
  return { top: best.top, bottom: best.bottom };
}

const layoutEntries = (json.sprites as { name: string; row: number; col: number }[])
  .map(s => {
    const { top, bottom } = contentRows(s.row, s.col);
    return `  ${s.name}: { row: ${s.row}, col: ${s.col}, top: ${top}, bottom: ${bottom} },`;
  })
  .join("\n");

const module = `// GENERATED by tools/gen-coral-atlas.ts — do not edit by hand.
// The coral sprite sheet: a ${cols}x${rows} grid of ${cell}px cells. Every cell is a
// complete standalone coral resting on its own rocky foot, placed individually on
// the sand. Rows 0–1 are orange branching/finger corals, row 2 the purple sea fans
// and green plate corals, row 3 the pink/teal/yellow polyp & sponge clusters.
// top/bottom are the y offsets of the first/last opaque row of the coral's main
// body (disconnected atlas-edge specks are ignored so sprites sit flush on sand).
// Layout derived from art/coral-atlas-128.json.
export const CORAL_ATLAS = "data:image/png;base64,${b64}";
export const CORAL_ATLAS_CELL = ${cell};
export const CORAL_ATLAS_COLS = ${cols};
export const CORAL_ATLAS_ROWS = ${rows};
export const CORAL_ATLAS_LAYOUT: Record<string, { row: number; col: number; top: number; bottom: number }> = {
${layoutEntries}
};
`;

writeFileSync(OUT, module);
console.log(`wrote ${OUT} (${(module.length / 1024).toFixed(0)} KB)`);
