// Bake the generated 3x2 hermit-crab walk cycle into a compact runtime sheet.
//
// The source was deliberately generated with one rigid shell/body anchor and an
// identical foot baseline in every panel. We crop every panel with the same
// rectangle (rather than fitting each silhouette independently), then resize all
// six frames at one shared scale. That preserves the body mass and ground contact
// while the legs reach and recover around it.
import { readFileSync, writeFileSync } from "node:fs";
import { decodePng, encodePng } from "./png";

const SRC = "art/hermit-crab-atlas-transparent.png";
const OUT = "art/hermit-crab-atlas-128.png";
const OUT_TS = "src/hermitCrabAtlas.ts";
const OUT_META = "art/hermit-crab-atlas-128.json";

const SOURCE_COLS = 3;
const SOURCE_ROWS = 2;
const FRAMES = 6;
const TILE = 128;

// Fixed panel-local crop measured from the generated source. The top row begins
// at y=0 and the lower at y=627. Both rows use these same local coordinates.
const CROP_X = 8;
const CROP_Y = 210;
const CROP_W = 372;
const CROP_H = 279;
const LOWER_ROW_Y_ADJUST = -159; // lower-row subject sits 159px higher in its panel

const DRAW_X = 6;
const DRAW_Y = 34;
const DRAW_W = 116;
const DRAW_H = 87;
const GROUND_LINE = 118; // runtime y occupied by the lowest planted foot

type Buf = { data: Uint8Array; w: number; h: number };
const src = decodePng(readFileSync(SRC));
const panelW = src.w / SOURCE_COLS;
const panelH = src.h / SOURCE_ROWS;
if (!Number.isInteger(panelW) || !Number.isInteger(panelH))
  throw new Error(`expected an exact 3x2 source grid, got ${src.w}x${src.h}`);

function crop(x0: number, y0: number, w: number, h: number): Buf {
  const data = new Uint8Array(w * h * 4);
  for (let y = 0; y < h; y++) {
    const from = ((y0 + y) * src.w + x0) * 4;
    data.set(src.rgba.subarray(from, from + w * 4), y * w * 4);
  }
  return { data, w, h };
}

// Premultiplied-alpha area sampling keeps the generated pixel clusters crisp at
// the smaller runtime size without pulling dark colour through transparent edges.
function resize(input: Buf, outW: number, outH: number): Buf {
  const data = new Uint8Array(outW * outH * 4);
  const scaleX = input.w / outW;
  const scaleY = input.h / outH;
  for (let dy = 0; dy < outH; dy++) {
    const sy0 = dy * scaleY;
    const sy1 = (dy + 1) * scaleY;
    for (let dx = 0; dx < outW; dx++) {
      const sx0 = dx * scaleX;
      const sx1 = (dx + 1) * scaleX;
      let areaSum = 0;
      let alphaSum = 0;
      let red = 0;
      let green = 0;
      let blue = 0;
      for (let sy = Math.floor(sy0); sy < Math.ceil(sy1); sy++) {
        const wy = Math.max(0, Math.min(sy1, sy + 1) - Math.max(sy0, sy));
        for (let sx = Math.floor(sx0); sx < Math.ceil(sx1); sx++) {
          const wx = Math.max(0, Math.min(sx1, sx + 1) - Math.max(sx0, sx));
          const area = wx * wy;
          if (!area) continue;
          const si = (sy * input.w + sx) * 4;
          const alpha = input.data[si + 3] / 255;
          areaSum += area;
          alphaSum += alpha * area;
          red += input.data[si] * alpha * area;
          green += input.data[si + 1] * alpha * area;
          blue += input.data[si + 2] * alpha * area;
        }
      }
      if (!alphaSum) continue;
      const di = (dy * outW + dx) * 4;
      data[di] = Math.round(red / alphaSum);
      data[di + 1] = Math.round(green / alphaSum);
      data[di + 2] = Math.round(blue / alphaSum);
      data[di + 3] = Math.round((alphaSum / areaSum) * 255);
    }
  }
  return { data, w: outW, h: outH };
}

const sheet = new Uint8Array(TILE * FRAMES * TILE * 4);
for (let frame = 0; frame < FRAMES; frame++) {
  const col = frame % SOURCE_COLS;
  const row = Math.floor(frame / SOURCE_COLS);
  const sourceY = row * panelH + CROP_Y + (row ? LOWER_ROW_Y_ADJUST : 0);
  const pose = resize(
    crop(col * panelW + CROP_X, sourceY, CROP_W, CROP_H),
    DRAW_W,
    DRAW_H,
  );
  for (let y = 0; y < DRAW_H; y++)
    for (let x = 0; x < DRAW_W; x++) {
      const si = (y * DRAW_W + x) * 4;
      if (pose.data[si + 3] === 0) continue;
      const di = ((DRAW_Y + y) * (TILE * FRAMES) + frame * TILE + DRAW_X + x) * 4;
      sheet.set(pose.data.subarray(si, si + 4), di);
    }
}

const png = encodePng(sheet, TILE * FRAMES, TILE);
writeFileSync(OUT, png);
const b64 = Buffer.from(png).toString("base64");
writeFileSync(
  OUT_TS,
  `// GENERATED by tools/gen-hermit-crab-atlas.ts - do not edit by hand.\n` +
    `// Six identity-stable side-walking poses, sharing one scale and foot line.\n` +
    `export const HERMIT_CRAB_ATLAS = "data:image/png;base64,${b64}";\n` +
    `export const HERMIT_CRAB_FRAMES = ${FRAMES};\n` +
    `export const HERMIT_CRAB_TILE = ${TILE};\n` +
    `export const HERMIT_CRAB_GROUND_OFFSET = ${GROUND_LINE - TILE / 2};\n`,
);
writeFileSync(
  OUT_META,
  JSON.stringify(
    {
      name: "hermit-crab",
      layout: { columns: FRAMES, rows: 1, tile: TILE },
      animation: { walk: { from: 0, to: FRAMES - 1, loop: true } },
      groundLine: GROUND_LINE,
      source: SRC,
    },
    null,
    2,
  ) + "\n",
);
console.log(`wrote ${OUT}, ${OUT_TS}, and ${OUT_META}`);
