// One-off generator: embed art/fish-extra-atlas-128.png as a base64 data URL in
// src/fishExtraAtlas.ts, and bake the sprite layout from art/fish-extra-atlas-128.json.
// Re-run if the source atlas or JSON changes.
import { readFileSync, writeFileSync } from "node:fs";

const SRC_PNG  = "art/fish-extra-atlas-128.png";
const SRC_JSON = "art/fish-extra-atlas-128.json";
const OUT      = "src/fishExtraAtlas.ts";

const b64 = readFileSync(SRC_PNG).toString("base64");
const json = JSON.parse(readFileSync(SRC_JSON, "utf8"));

const cell = 128;
const cols: number = json.columns;
const rows: number = json.rows;

const layoutEntries = (json.sprites as { name: string; row: number; col: number }[])
  .map(s => `  ${s.name}: { row: ${s.row}, col: ${s.col} },`)
  .join("\n");

const module = `// GENERATED by tools/gen-fish-extra-atlas.ts — do not edit by hand.
// The extra fish sprite sheet: a ${cols}x${rows} grid of ${cell}px cells, one pixel-art fish per cell,
// every fish facing left. Embedded as a base64 data URL so there is no asset
// pipeline. At load, each cell is copied at native resolution and given a baked
// species-profiled four-frame swim cycle (see fish.ts). Layout is derived from art/fish-extra-atlas-128.json.
export const FISH_EXTRA_ATLAS = "data:image/png;base64,${b64}";
export const FISH_EXTRA_ATLAS_CELL = ${cell};
export const FISH_EXTRA_ATLAS_COLS = ${cols};
export const FISH_EXTRA_ATLAS_ROWS = ${rows};
export const FISH_EXTRA_ATLAS_LAYOUT: Record<string, { row: number; col: number }> = {
${layoutEntries}
};
`;

writeFileSync(OUT, module);
console.log(`wrote ${OUT} (${(module.length / 1024).toFixed(0)} KB)`);
