// One-off generator: embed art/coral-atlas-128.png as a base64 data URL in
// src/coralsAtlas.ts, and bake the sprite layout + tight bounding boxes from
// art/coral-atlas-128.json. Re-run if the source atlas or JSON changes.
import { readFileSync, writeFileSync } from "node:fs";
import { decodePng } from "./png";

const SRC_PNG  = "art/coral-atlas-128.png";
const SRC_JSON = "art/coral-atlas-128.json";
const OUT      = "src/coralsAtlas.ts";

const pngBuf = readFileSync(SRC_PNG);
const b64 = pngBuf.toString("base64");
const { rgba, w } = decodePng(pngBuf);
const json = JSON.parse(readFileSync(SRC_JSON, "utf8"));

const cell: number = json.tileSize;
const cols: number = json.columns;
const rows: number = json.rows;

// Compute the tight vertical extent (from cell top) for each sprite so
// coralBlits() can stack pieces so they visually touch rather than spacing
// by full cell height.
function contentRows(row: number, col: number): { top: number; bottom: number } {
  const x0 = col * cell;
  const y0 = row * cell;
  let minY = cell, maxY = -1;
  for (let y = 0; y < cell; y++) {
    for (let x = 0; x < cell; x++) {
      if (rgba[((y0 + y) * w + (x0 + x)) * 4 + 3] > 0) {
        if (y < minY) minY = y;
        if (y > maxY) maxY = y;
      }
    }
  }
  return maxY < 0 ? { top: 0, bottom: cell - 1 } : { top: minY, bottom: maxY };
}

const layoutEntries = (json.sprites as { name: string; row: number; col: number }[])
  .map(s => {
    const { top, bottom } = contentRows(s.row, s.col);
    return `  ${s.name}: { row: ${s.row}, col: ${s.col}, top: ${top}, bottom: ${bottom} },`;
  })
  .join("\n");

const module = `// GENERATED by tools/gen-coral-atlas.ts — do not edit by hand.
// The coral sprite sheet: a ${cols}x${rows} grid of ${cell}px cells. Rows 0–1 are
// building-block parts (base, segments, junctions, connectors, endings) designed
// to be stacked into taller composed corals. Rows 2–3 are standalone small items
// (sea fans, plate corals, fillers) placed individually on the sand.
// top/bottom are the y offsets of the first/last non-transparent row within the cell.
// Layout derived from art/coral-atlas-128.json.
export const CORAL_ATLAS = "data:image/png;base64,${b64}";
export const CORAL_ATLAS_CELL = ${cell};
export const CORAL_ATLAS_COLS = ${cols};
export const CORAL_ATLAS_ROWS = ${rows};
export const CORAL_ATLAS_LAYOUT: Record<string, { row: number; col: number; top: number; bottom: number }> = {
${layoutEntries}
};
`;

writeFileSync(OUT, module);
console.log(`wrote ${OUT} (${(module.length / 1024).toFixed(0)} KB)`);
