// Embed the normalized bonus fish atlas as a generated TypeScript module.
// Re-run after changing the source atlas or its JSON layout.
import { readFileSync, writeFileSync } from "node:fs";

const SRC_PNG = "art/fish-bonus-atlas-128.png";
const SRC_JSON = "art/fish-bonus-atlas-128.json";
const OUT = "src/fishBonusAtlas.ts";

const b64 = readFileSync(SRC_PNG).toString("base64");
const json = JSON.parse(readFileSync(SRC_JSON, "utf8"));
const cell: number = json.tileSize;
const cols: number = json.columns;
const rows: number = json.rows;
const layoutEntries = (json.sprites as { name: string; row: number; col: number }[])
  .map((sprite) => `  ${sprite.name}: { row: ${sprite.row}, col: ${sprite.col} },`)
  .join("\n");

const module = `// GENERATED by tools/gen-fish-bonus-atlas.ts — do not edit by hand.
// The bonus fish sprite sheet: a ${cols}x${rows} grid of ${cell}px cells, one pixel-art fish per cell,
// every fish facing left. At load, each cell receives the shared species-profiled
// four-frame swim cycle. Layout is derived from art/fish-bonus-atlas-128.json.
export const FISH_BONUS_ATLAS = "data:image/png;base64,${b64}";
export const FISH_BONUS_ATLAS_CELL = ${cell};
export const FISH_BONUS_ATLAS_COLS = ${cols};
export const FISH_BONUS_ATLAS_ROWS = ${rows};
export const FISH_BONUS_ATLAS_LAYOUT: Record<string, { row: number; col: number }> = {
${layoutEntries}
};
`;

writeFileSync(OUT, module);
console.log(`wrote ${OUT} (${(module.length / 1024).toFixed(0)} KB)`);
