// Bake the generated 3x2 nudibranch crawl cycle into a compact runtime sheet.
// The game calls it a sea snail. Frames are aligned on the dense lower body so
// moving rhinophores and gills cannot pull the apparent body anchor sideways.
import { readFileSync, writeFileSync } from "node:fs";
import { decodePng, encodePng } from "./png";

const SRC = "art/sea-snail-atlas-transparent.png";
const OUT = "art/sea-snail-atlas-128.png";
const OUT_TS = "src/seaSnailAtlas.ts";
const OUT_META = "art/sea-snail-atlas-128.json";
const COLS = 3;
const ROWS = 2;
const FRAMES = 6;
const TILE = 128;
const CROP_W = 468;
const CROP_H = 240;
const CROP_TOP = [180, 67] as const;
const BASELINE = [408, 295] as const;
const DRAW_W = 86;
const DRAW_H = 44;
const DRAW_X = 21;
const GROUND_LINE = 108;
const DRAW_Y = GROUND_LINE - Math.round(((BASELINE[0] - CROP_TOP[0]) / CROP_H) * DRAW_H);

type Buf = { data: Uint8Array; w: number; h: number };
const src = decodePng(readFileSync(SRC));
const panelW = src.w / COLS;
const panelH = src.h / ROWS;
if (panelW !== 512 || panelH !== 512)
  throw new Error(`expected a 1536x1024 3x2 source, got ${src.w}x${src.h}`);

// Alpha-weighted mean x of the broad foot/lower mantle. This region excludes
// the independently moving rhinophores and gill fan.
function bodyAnchorX(col: number, row: number): number {
  const y0 = BASELINE[row] - 70;
  const y1 = BASELINE[row];
  let sumX = 0;
  let sumA = 0;
  for (let y = y0; y < y1; y++)
    for (let x = 0; x < panelW; x++) {
      const a = src.rgba[(((row * panelH + y) * src.w + col * panelW + x) * 4) + 3];
      if (a <= 64) continue;
      sumX += x * a;
      sumA += a;
    }
  if (!sumA) throw new Error(`empty lower-body anchor in panel ${row},${col}`);
  return sumX / sumA;
}

function crop(x0: number, y0: number, w: number, h: number): Buf {
  const data = new Uint8Array(w * h * 4);
  for (let y = 0; y < h; y++) {
    const from = ((y0 + y) * src.w + x0) * 4;
    data.set(src.rgba.subarray(from, from + w * 4), y * w * 4);
  }
  return { data, w, h };
}

function resize(input: Buf, outW: number, outH: number): Buf {
  const data = new Uint8Array(outW * outH * 4);
  const scaleX = input.w / outW;
  const scaleY = input.h / outH;
  for (let dy = 0; dy < outH; dy++) {
    const sy0 = dy * scaleY;
    const sy1 = (dy + 1) * scaleY;
    for (let dx = 0; dx < outW; dx++) {
      const sx0 = dx * scaleX;
      const sx1 = (dx + 1) * scaleX;
      let areaSum = 0;
      let alphaSum = 0;
      let red = 0;
      let green = 0;
      let blue = 0;
      for (let sy = Math.floor(sy0); sy < Math.ceil(sy1); sy++) {
        const wy = Math.max(0, Math.min(sy1, sy + 1) - Math.max(sy0, sy));
        for (let sx = Math.floor(sx0); sx < Math.ceil(sx1); sx++) {
          const wx = Math.max(0, Math.min(sx1, sx + 1) - Math.max(sx0, sx));
          const area = wx * wy;
          if (!area) continue;
          const si = (sy * input.w + sx) * 4;
          const alpha = input.data[si + 3] / 255;
          areaSum += area;
          alphaSum += alpha * area;
          red += input.data[si] * alpha * area;
          green += input.data[si + 1] * alpha * area;
          blue += input.data[si + 2] * alpha * area;
        }
      }
      if (!alphaSum) continue;
      const di = (dy * outW + dx) * 4;
      data[di] = Math.round(red / alphaSum);
      data[di + 1] = Math.round(green / alphaSum);
      data[di + 2] = Math.round(blue / alphaSum);
      data[di + 3] = Math.round((alphaSum / areaSum) * 255);
    }
  }
  return { data, w: outW, h: outH };
}

const sheetW = TILE * FRAMES;
const sheet = new Uint8Array(sheetW * TILE * 4);
for (let frame = 0; frame < FRAMES; frame++) {
  const col = frame % COLS;
  const row = Math.floor(frame / COLS);
  const anchor = bodyAnchorX(col, row);
  const cropX = Math.max(0, Math.min(panelW - CROP_W, Math.round(anchor - CROP_W / 2)));
  const pose = resize(
    crop(col * panelW + cropX, row * panelH + CROP_TOP[row], CROP_W, CROP_H),
    DRAW_W,
    DRAW_H,
  );
  for (let y = 0; y < DRAW_H; y++)
    for (let x = 0; x < DRAW_W; x++) {
      const si = (y * DRAW_W + x) * 4;
      if (pose.data[si + 3] === 0) continue;
      const di = ((DRAW_Y + y) * sheetW + frame * TILE + DRAW_X + x) * 4;
      sheet.set(pose.data.subarray(si, si + 4), di);
    }
}

const png = encodePng(sheet, sheetW, TILE);
writeFileSync(OUT, png);
const b64 = Buffer.from(png).toString("base64");
writeFileSync(
  OUT_TS,
  `// GENERATED by tools/gen-sea-snail-atlas.ts - do not edit by hand.\n` +
    `// Six body-anchored nudibranch crawl poses with one shared foot line.\n` +
    `export const SEA_SNAIL_ATLAS = "data:image/png;base64,${b64}";\n` +
    `export const SEA_SNAIL_FRAMES = ${FRAMES};\n` +
    `export const SEA_SNAIL_TILE = ${TILE};\n` +
    `export const SEA_SNAIL_GROUND_OFFSET = ${GROUND_LINE - TILE / 2};\n`,
);
writeFileSync(
  OUT_META,
  JSON.stringify(
    {
      name: "sea-snail",
      subject: "nudibranch",
      layout: { columns: FRAMES, rows: 1, tile: TILE },
      animation: { crawl: { from: 0, to: FRAMES - 1, loop: true } },
      groundLine: GROUND_LINE,
      source: SRC,
    },
    null,
    2,
  ) + "\n",
);
console.log(`wrote ${OUT}, ${OUT_TS}, and ${OUT_META}`);
