// One-off generator: embed art/sea-creatures-atlas-128.png as a base64 data URL.
// Re-run if the source atlas changes.
import { readFileSync, writeFileSync } from "node:fs";

const SRC = "art/sea-creatures-atlas-128.png";
const OUT = "src/seaCreaturesAtlas.ts";

const b64 = readFileSync(SRC).toString("base64");
const module = `// GENERATED by tools/gen-sea-creatures-atlas.ts - do not edit by hand.
// The sea-creature sprite sheet: a 3x2 grid of 128px cells. The nautilus (4) and
// jellyfish (0) are cropped from this atlas and animated at load in cephalopod.ts.
export const SEA_CREATURES_ATLAS = "data:image/png;base64,${b64}";
export const SEA_CREATURES_ATLAS_COLS = 3;
export const SEA_CREATURES_ATLAS_CELL = 128;
export const SEA_CREATURE_NAUTILUS_INDEX = 4;
export const SEA_CREATURE_JELLYFISH_INDEX = 0;
`;

writeFileSync(OUT, module);
console.log(`wrote ${OUT} (${(module.length / 1024).toFixed(0)} KB)`);
