// One-off generator: embed art/fish-atlas-128.png as a base64 data URL in
// src/fishAtlas.ts. Re-run if the source atlas changes. The level/identity table
// is hand-authored in src/fish.ts, not here — this file only carries the pixels.
import { readFileSync, writeFileSync } from "node:fs";

const SRC = "art/fish-atlas-128.png";
const OUT = "src/fishAtlas.ts";

const b64 = readFileSync(SRC).toString("base64");
const module = `// GENERATED by tools/gen-fish-atlas.ts — do not edit by hand.
// The fish sprite sheet: a 3x4 grid of 128px cells, one realistic fish per cell,
// every fish facing left. Embedded as a base64 data URL so there is no asset
// pipeline (same approach as the nautilus atlas). At load, each cell is smooth-
// downscaled to fish size and given a baked tail-swish swim cycle (see fish.ts).
export const FISH_ATLAS = "data:image/png;base64,${b64}";
export const FISH_ATLAS_COLS = 3;
export const FISH_ATLAS_ROWS = 4;
export const FISH_ATLAS_CELL = 128;
`;

writeFileSync(OUT, module);
console.log(`wrote ${OUT} (${(module.length / 1024).toFixed(0)} KB)`);
