// Embed the normalized small-props atlas and bake each prop's tight vertical
// content bounds. The backdrop uses the bottom bound as its sand contact point.
import { readFileSync, writeFileSync } from "node:fs";
import { decodePng } from "./png";

const SRC_PNG = "art/small-props-atlas-128.png";
const SRC_JSON = "art/small-props-atlas-128.json";
const OUT = "src/smallPropsAtlas.ts";

const png = readFileSync(SRC_PNG);
const b64 = png.toString("base64");
const { rgba, w } = decodePng(png);
const json = JSON.parse(readFileSync(SRC_JSON, "utf8"));
const cell: number = json.tileSize;
const cols: number = json.columns;
const rows: number = json.rows;

function contentBounds(row: number, col: number) {
  let top = cell;
  let bottom = -1;
  for (let y = 0; y < cell; y++) {
    for (let x = 0; x < cell; x++) {
      if (rgba[(((row * cell + y) * w) + col * cell + x) * 4 + 3] < 16) continue;
      top = Math.min(top, y);
      bottom = Math.max(bottom, y);
    }
  }
  if (bottom < top)
    return { top: 0, bottom: cell - 1, contactLeft: 0, contactRight: cell - 1 };

  // Only the lowest band is the physical contact footprint. Using the full
  // silhouette would count overhanging shell tips and anchor hooks as support.
  let contactLeft = cell;
  let contactRight = -1;
  for (let y = Math.max(top, bottom - 10); y <= bottom; y++) {
    for (let x = 0; x < cell; x++) {
      if (rgba[(((row * cell + y) * w) + col * cell + x) * 4 + 3] < 16) continue;
      contactLeft = Math.min(contactLeft, x);
      contactRight = Math.max(contactRight, x);
    }
  }
  return { top, bottom, contactLeft, contactRight };
}

const entries = (json.sprites as { name: string; row: number; col: number }[])
  .map((sprite) => {
    const { top, bottom, contactLeft, contactRight } = contentBounds(sprite.row, sprite.col);
    return `  ${sprite.name}: { row: ${sprite.row}, col: ${sprite.col}, top: ${top}, bottom: ${bottom}, contactLeft: ${contactLeft}, contactRight: ${contactRight} },`;
  })
  .join("\n");

const module = `// GENERATED by tools/gen-small-props-atlas.ts — do not edit by hand.
// Sixteen grounded side-view seabed props in a ${cols}x${rows} grid of ${cell}px cells.
// top/bottom are tight opaque-row bounds; contactLeft/contactRight describe the
// lowest illustrated sand footprint used to settle props across curved dunes.
export const SMALL_PROPS_ATLAS = "data:image/png;base64,${b64}";
export const SMALL_PROPS_ATLAS_CELL = ${cell};
export const SMALL_PROPS_ATLAS_LAYOUT: Record<string, { row: number; col: number; top: number; bottom: number; contactLeft: number; contactRight: number }> = {
${entries}
};
`;

writeFileSync(OUT, module);
console.log(`wrote ${OUT} (${(module.length / 1024).toFixed(0)} KB)`);
